//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v6.21.6150.29665 (NJsonSchema v5.12.6149.949) (http://NSwag.org)
// </auto-generated>
//----------------------

using System.Threading.Tasks;

namespace Threax.AspNetCore.IdServerMetadata.Client
{
    public interface IMetadataClient
    {
        Task<ClientMetadata> ClientAsync(string baseUrl);
        Task<ClientMetadata> ClientCredentialsAsync(string baseUrl);
        Task<ApiResourceMetadata> ScopeAsync(string baseUrl);
    }
}